/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem { 'productId' : ProductId, 'quantity' : bigint }
export type Category = string;
export interface Product {
  'id' : ProductId,
  'featured' : boolean,
  'inStock' : boolean,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : Category,
  'rating' : number,
  'price' : number,
}
export type ProductId = bigint;
export interface _SERVICE {
  'addProduct' : ActorMethod<
    [string, string, Category, number, string, boolean, number, boolean],
    ProductId
  >,
  'addToCart' : ActorMethod<[ProductId, bigint], undefined>,
  'addToWishlist' : ActorMethod<[ProductId], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'deleteProduct' : ActorMethod<[ProductId], boolean>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getFeaturedProducts' : ActorMethod<[], Array<Product>>,
  'getProductById' : ActorMethod<[ProductId], [] | [Product]>,
  'getProductsByCategory' : ActorMethod<[Category], Array<Product>>,
  'getWishlist' : ActorMethod<[], Array<ProductId>>,
  'initialize' : ActorMethod<[], boolean>,
  'removeFromCart' : ActorMethod<[ProductId], undefined>,
  'removeFromWishlist' : ActorMethod<[ProductId], undefined>,
  'updateProduct' : ActorMethod<
    [
      ProductId,
      string,
      string,
      Category,
      number,
      string,
      boolean,
      number,
      boolean,
    ],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];