/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Text;
export const ProductId = IDL.Nat;
export const Product = IDL.Record({
  'id' : ProductId,
  'featured' : IDL.Bool,
  'inStock' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : Category,
  'rating' : IDL.Float64,
  'price' : IDL.Float64,
});
export const CartItem = IDL.Record({
  'productId' : ProductId,
  'quantity' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        Category,
        IDL.Float64,
        IDL.Text,
        IDL.Bool,
        IDL.Float64,
        IDL.Bool,
      ],
      [ProductId],
      [],
    ),
  'addToCart' : IDL.Func([ProductId, IDL.Nat], [], []),
  'addToWishlist' : IDL.Func([ProductId], [], []),
  'clearCart' : IDL.Func([], [], []),
  'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductById' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([Category], [IDL.Vec(Product)], ['query']),
  'getWishlist' : IDL.Func([], [IDL.Vec(ProductId)], ['query']),
  'initialize' : IDL.Func([], [IDL.Bool], []),
  'removeFromCart' : IDL.Func([ProductId], [], []),
  'removeFromWishlist' : IDL.Func([ProductId], [], []),
  'updateProduct' : IDL.Func(
      [
        ProductId,
        IDL.Text,
        IDL.Text,
        Category,
        IDL.Float64,
        IDL.Text,
        IDL.Bool,
        IDL.Float64,
        IDL.Bool,
      ],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Text;
  const ProductId = IDL.Nat;
  const Product = IDL.Record({
    'id' : ProductId,
    'featured' : IDL.Bool,
    'inStock' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : Category,
    'rating' : IDL.Float64,
    'price' : IDL.Float64,
  });
  const CartItem = IDL.Record({
    'productId' : ProductId,
    'quantity' : IDL.Nat,
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          Category,
          IDL.Float64,
          IDL.Text,
          IDL.Bool,
          IDL.Float64,
          IDL.Bool,
        ],
        [ProductId],
        [],
      ),
    'addToCart' : IDL.Func([ProductId, IDL.Nat], [], []),
    'addToWishlist' : IDL.Func([ProductId], [], []),
    'clearCart' : IDL.Func([], [], []),
    'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductById' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getWishlist' : IDL.Func([], [IDL.Vec(ProductId)], ['query']),
    'initialize' : IDL.Func([], [IDL.Bool], []),
    'removeFromCart' : IDL.Func([ProductId], [], []),
    'removeFromWishlist' : IDL.Func([ProductId], [], []),
    'updateProduct' : IDL.Func(
        [
          ProductId,
          IDL.Text,
          IDL.Text,
          Category,
          IDL.Float64,
          IDL.Text,
          IDL.Bool,
          IDL.Float64,
          IDL.Bool,
        ],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };